workflows:
  android-unity:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      vars:
        UNITY_VERSION: 2022.3.22f1
    scripts:
      - name: Build Unity Android
        script: |
          unity-builder build-android -v $UNITY_VERSION
    artifacts:
      - build/*.apk